language: objective-c

os: osx
osx_image: xcode12.2

script:
  - xcodebuild build

before_deploy:
  - pushd build/Release > /dev/null
  - zip -r "Micro Stream Player.zip" "Micro Stream Player.app"
  - popd > /dev/null

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  target_commitish: master
  file: "build/Release/Micro Stream Player.zip"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
